

spring:
  datasource:
    url: jdbc:mysql://localhost/spring
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  freemarker:
    cache: false
    suffix: .html
    content-type: text/html
    check-template-location: true
    template-loader-path: classpath:templates/
    template-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /demo
